"use client";

import { useEffect, useState } from "react";
import { VeritasScore } from "@/components/dashboard/VeritasScore";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Globe, AlertTriangle, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DEMO_DATA, ReportData } from "@/lib/demo-data"; // Import the data
import { Skeleton } from "@/components/ui/skeleton";

export default function DashboardOverviewPage() {
    const [data, setData] = useState<ReportData | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        // Hydrate data from session storage (Generated by API)
        const storedResult = sessionStorage.getItem("analysisResult");

        if (storedResult) {
            setData(JSON.parse(storedResult));
            setLoading(false);
        } else {
            // Fallback for direct access without upload (keep demo logic safe)
            const scenario = sessionStorage.getItem("demoScenario") || "vietnam";
            const selectedData = DEMO_DATA[scenario] || DEMO_DATA["vietnam"];
            setTimeout(() => {
                setData(selectedData);
                setLoading(false);
            }, 500);
        }
    }, []);

    if (loading) {
        return <div className="p-8"><Skeleton className="h-64 w-full bg-slate-800" /></div>;
    }

    // Default to Vietnam data if null (shouldn't happen)
    const activeData = data || DEMO_DATA["vietnam"];

    return (
        <div className="p-8 space-y-8 animate-in fade-in duration-500">
            {/* Page Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-heading font-bold text-white mb-2">Verification Overview</h1>
                    <div className="flex items-center gap-2 text-slate-400 text-sm">
                        <span>Report ID: {activeData.id}</span>
                        <span>•</span>
                        <span className="flex items-center gap-1"><Globe className="h-3 w-3" /> {activeData.location}</span>
                        <span>•</span>
                        <span className="text-emerald-400 bg-emerald-400/10 px-2 py-0.5 rounded text-xs font-bold">LIVE ANALYSIS</span>
                    </div>
                </div>
                <div className="flex gap-3">
                    <Button variant="outline" className="border-slate-700 text-slate-300 hover:text-white" onClick={() => alert("Share Link copied to clipboard!")}>Share Report</Button>
                    <Button onClick={() => alert("Downloading PDF Report...")}>Export PDF</Button>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Main Score Card */}
                <VeritasScore score={activeData.score} verdict={activeData.verdict} />

                {/* KPI Cards */}
                <div className="lg:col-span-2 grid grid-cols-1 md:grid-cols-2 gap-4">
                    <Card className="bg-gradient-to-br from-slate-900/80 to-slate-900/40 border-slate-800/60 backdrop-blur-md hover:border-red-500/30 transition-all group relative overflow-hidden">
                        <div className="absolute top-0 right-0 w-24 h-24 bg-red-500/10 rounded-full blur-2xl -mr-12 -mt-12 pointer-events-none group-hover:bg-red-500/20 transition-colors"></div>
                        <CardHeader className="pb-2">
                            <CardTitle className="text-sm font-medium text-slate-400 uppercase tracking-wider flex items-center gap-2">
                                <AlertTriangle className="h-4 w-4 text-red-500" /> Detected Lies
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-white to-slate-300 mb-1">{activeData.lies}</div>
                            {activeData.lies > 0 ? (
                                <p className="text-xs text-red-400 font-medium flex items-center gap-1 bg-red-500/10 py-1 px-2 rounded-full w-fit">
                                    Critical Discrepancies Found
                                </p>
                            ) : (
                                <p className="text-xs text-emerald-400 font-medium flex items-center gap-1 bg-emerald-500/10 py-1 px-2 rounded-full w-fit">
                                    No discrepancies detected
                                </p>
                            )}
                        </CardContent>
                    </Card>
                    <Card className="bg-gradient-to-br from-slate-900/80 to-slate-900/40 border-slate-800/60 backdrop-blur-md hover:border-amber-500/30 transition-all group relative overflow-hidden">
                        <div className="absolute top-0 right-0 w-24 h-24 bg-amber-500/10 rounded-full blur-2xl -mr-12 -mt-12 pointer-events-none group-hover:bg-amber-500/20 transition-colors"></div>
                        <CardHeader className="pb-2">
                            <CardTitle className="text-sm font-medium text-slate-400 uppercase tracking-wider flex items-center gap-2">
                                <CheckCircle2 className="h-4 w-4 text-amber-500" /> Compliance Gap
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-white to-slate-300 mb-1">{activeData.missingFields} <span className="text-lg text-slate-500 font-normal">Fields</span></div>
                            {activeData.missingFields > 0 ? (
                                <p className="text-xs text-amber-400 font-medium flex items-center gap-1 bg-amber-500/10 py-1 px-2 rounded-full w-fit">
                                    Missing Mandatory Data
                                </p>
                            ) : (
                                <p className="text-xs text-emerald-400 font-medium flex items-center gap-1 bg-emerald-500/10 py-1 px-2 rounded-full w-fit">
                                    Fully Compliant
                                </p>
                            )}
                        </CardContent>
                    </Card>
                    <Card className="bg-slate-900/40 border-slate-800 md:col-span-2">
                        <CardHeader>
                            <CardTitle className="text-white">Executive Summary</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <p className="text-slate-400 leading-relaxed">
                                {activeData.summary}
                            </p>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    );
}
